# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ require
version: '2.0'

services:
  sleutelkastje:
    environment:
      DATABASE_HOST: "db"
      DATABASE_USER: "test"
      DATABASE_PASSWORD: "test"
      VIRTUAL_HOST: "sleutelkast.sd.di.huc.knaw.nl"
    build: .
    ports:
      - "3010:5000"

  db:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "sleutelkastje"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./psql:/docker-entrypoint-initdb.d"

volumes:
  db-data:

