# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ require
version: '2'

services:
  sleutelkastje:
    environment:
      DATABASE_HOST: "db"
      DATABASE_USER: "test"
      DATABASE_PASSWORD: "test"
      VIRTUAL_HOST: "sleutelkast.sd.di.huc.knaw.nl"
      APP_DOMAIN: "https://sleutelkast.sd.di.huc.knaw.nl"
      OIDC_SERVER: "https://testauthentication.di.huc.knaw.nl"
      OIDC_CLIENT_ID: "nl_knaw_huc_di_sd_sleutelkast" 
      OIDC_CLIENT_SECRET: "b47e55ae-4634-11ed-a804-5329bcd6a806" 
    build: .
    ports:
      - "3010:5000"
    networks:
      - sleutelkast_network

  todo:
    environment:
      VIRTUAL_HOST: "todo.sd.di.huc.knaw.nl"
      APP_DOMAIN: "https://todo.sd.di.huc.knaw.nl"
      OIDC_SERVER: "https://testauthentication.di.huc.knaw.nl"
      OIDC_CLIENT_ID: "nl_knaw_huc_di_sd_todo" 
      OIDC_CLIENT_SECRET: "5RKBN2siBqLq9MUHXlKZ" 
    build: ./todo
    ports:
      - "3011:5001"
    networks:
      - sleutelkast_network

  db:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "sleutelkastje"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./psql:/docker-entrypoint-initdb.d"
    networks:
      - sleutelkast_network

volumes:
  db-data:

networks:
  sleutelkast_network:
    external:
      name: nginxproxynetwork
