# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ require
version: '2'

services:
  sleutelkastje:
    environment:
      DATABASE_HOST: "db"
      DATABASE_USER: "test"
      DATABASE_PASSWORD: "test"
      APP_DOMAIN: "https://sleutelkast.sd.di.huc.knaw.nl"
      OIDC_SERVER: "https://testauthentication.di.huc.knaw.nl"
      OIDC_CLIENT_ID: "nl_knaw_huc_di_sd_sleutelkast" 
      OIDC_CLIENT_SECRET: "b47e55ae-4634-11ed-a804-5329bcd6a806"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sleutelkast.entrypoints=http"
      - "traefik.http.routers.sleutelkast.rule=Host(`sleutelkast.sd.di.huc.knaw.nl`);PathRegexp(`(?i)^/(api|auth)`)"
    image: registry.diginfra.net/tsd/sleutelkastje:latest
    ports:
      - "3010:5000"
    depends_on:
      - db
    networks:
      - sleutelkast_network
  sk-frontend:
    build: frontend
    restart: unless-stopped
    ports:
      - "3020:80"
    environment:
      REACT_APP_API_BASE: "https://sleutelkast.sd.di.huc.knaw.nl"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sk-frontend.entrypoints=http"
      - "traefik.http.routers.sk-frontend.rule=Host(`sleutelkast.sd.di.huc.knaw.nl`)"
    networks:
      - sleutelkast_network
  sk-docs:
    build:
      context: .
      dockerfile: Dockerfile-docs
    ports:
      - "3021:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sk-docs.entrypoints=http"
      - "traefik.http.routers.sk-docs.rule=Host(`sleutelkast.sd.di.huc.knaw.nl`);PathPrefix(`/docs`)"
      - "traefik.http.middlewares.sk-docs.stripprefix.prefixes=/docs"
    networks:
      - sleutelkast_network

  todo:
    environment:
      VIRTUAL_HOST: "todo.sd.di.huc.knaw.nl"
      APP_DOMAIN: "https://todo.sd.di.huc.knaw.nl"
      OIDC_SERVER: "https://testauthentication.di.huc.knaw.nl"
      OIDC_CLIENT_ID: "nl_knaw_huc_di_sd_todo" 
      OIDC_CLIENT_SECRET: "5RKBN2siBqLq9MUHXlKZ" 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sleutelkast-todo.entrypoints=http"
      - "traefik.http.routers.sleutelkast-todo.rule=Host(`todo.sd.di.huc.knaw.nl`)"
    build: ./todo
    ports:
      - "3011:5001"
    networks:
      - sleutelkast_network

  todo-j:
    environment:
      VIRTUAL_HOST: "todo-j.sd.di.huc.knaw.nl"
      APP_DOMAIN: "https://todo-j.sd.di.huc.knaw.nl"
      OIDC_SERVER: "https://testauthentication.di.huc.knaw.nl"
      OIDC_CLIENT_ID: "nl_knaw_huc_di_sd_todo-j" 
      OIDC_CLIENT_SECRET: "5RKBN2siBqLq9MUHXlKZ" 
    image: registry.diginfra.net/tsd/sleutelkastje-todo-j:20240416
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sleutelkast-todo-j.entrypoints=http"
      - "traefik.http.routers.sleutelkast-todo-j.rule=Host(`todo-j.sd.di.huc.knaw.nl`)"
    # build: ./todo/java
    ports:
      - "3012:9000"
    networks:
      - sleutelkast_network

  db:
    build:
      context: .
      dockerfile: Dockerfile-psql
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "sleutelkastje"
    ports:
      - "5454:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - sleutelkast_network

volumes:
  db-data:

networks:
  sleutelkast_network:
    external: true
    name: traefik-public
