"""user passwords

Revision ID: 33692aa70451
Revises: 526eb13544e1
Create Date: 2024-08-28 09:57:02.546247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33692aa70451'
down_revision = '526eb13544e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eppn', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.JSON(), nullable=True))
        batch_op.create_unique_constraint(None, ['eppn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('eppn')

    # ### end Alembic commands ###
