"""association relations

Revision ID: 42900c7e6e1d
Revises: 3b8502593d88
Create Date: 2024-09-24 16:19:45.269976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42900c7e6e1d'
down_revision = '3b8502593d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_user_association',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('app_id', 'user_id')
    )
    op.create_table('user_item_association',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'user_id')
    )
    op.drop_table('user_item')
    op.drop_table('user_applications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_applications',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], name='user_applications_application_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_applications_user_id_fkey')
    )
    op.create_table('user_item',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='user_item_item_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_item_user_id_fkey')
    )
    op.drop_table('user_item_association')
    op.drop_table('application_user_association')
    # ### end Alembic commands ###
