"""setup database

Revision ID: 526eb13544e1
Revises: 
Create Date: 2024-08-28 09:15:06.042477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526eb13544e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_info', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mnemonic', sa.String(), nullable=False),
    sa.Column('credentials', sa.String(), nullable=False),
    sa.Column('redirect', sa.String(), nullable=False),
    sa.Column('functional_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['functional_admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_mnemonic'), ['mnemonic'], unique=True)

    op.create_table('key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_key_key'), ['key'], unique=True)

    op.create_table('invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitation_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitation_uuid'))

    op.drop_table('invitation')
    with op.batch_alter_table('key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_key_key'))

    op.drop_table('key')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_mnemonic'))

    op.drop_table('application')
    op.drop_table('user')
    # ### end Alembic commands ###
