"""application user role

Revision ID: 59ca42ead8ae
Revises: 42900c7e6e1d
Create Date: 2024-09-24 16:32:38.112942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ca42ead8ae'
down_revision = '42900c7e6e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_user_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_user_association', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
