"""key names

Revision ID: 693cbea9be81
Revises: 59ca42ead8ae
Create Date: 2024-09-25 11:27:03.879204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693cbea9be81'
down_revision = '59ca42ead8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_used', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key', schema=None) as batch_op:
        batch_op.drop_column('last_used')
        batch_op.drop_column('name')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
