"""key per app

Revision ID: 8f220bd87330
Revises: e164dc1076bb
Create Date: 2024-11-14 14:55:20.056389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f220bd87330'
down_revision = 'e164dc1076bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'application', ['application_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('application_id')

    # ### end Alembic commands ###
