"""api key hash

Revision ID: aa33f74af31a
Revises: d9910c18ba5e
Create Date: 2024-09-19 15:13:49.317028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa33f74af31a'
down_revision = 'd9910c18ba5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_hash', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('key_prefix', sa.String(), nullable=False))
        batch_op.drop_index('ix_key_key')
        batch_op.create_index(batch_op.f('ix_key_key_prefix'), ['key_prefix'], unique=True)
        batch_op.create_unique_constraint(None, ['key_hash'])
        batch_op.drop_column('key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_key_key_prefix'))
        batch_op.create_index('ix_key_key', ['key'], unique=True)
        batch_op.drop_column('key_prefix')
        batch_op.drop_column('key_hash')

    # ### end Alembic commands ###
