"""invitation item role configuration

Revision ID: e164dc1076bb
Revises: 693cbea9be81
Create Date: 2024-09-30 11:38:12.695709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e164dc1076bb'
down_revision = '693cbea9be81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_role_configuration', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_column('item_role_configuration')

    # ### end Alembic commands ###
